package tech.yac.core.domain;

/**
 * Represents an Application instance supported by YAC
*
* @author Vishal Mahajan
*/
public interface YacApplication {

    /**
     * Returns Application Type generated by an implemention
     *
     * @returns ApplicationType
     */
    ApplicationType getType();

    FrameworkType getFrameworkType();

    BuildTool getBuildTool();

    /**
     * Returns build tools supported by a given application type
     *
     * @returns array of BuildToolType
    */
    BuildToolType[] getSupportedBuildTools();
}
