/*
 * YAC -- Companion to build opinionated Java and SPA applications.
 * Copyright (C) 2024 Vishal Mahajan
 *
 * This package is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2 of the
 * license as found in the file LICENSE.
 *
 * This package is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package tech.yac.core.domain;

import tech.yac.core.domain.build.BuildTool;
import tech.yac.core.domain.build.BuildToolType;

/**
 * Represents an Application instance supported by YAC
*
* @author Vishal Mahajan
*/
public interface YacApplication {

    /**
     * Returns Application Type generated by an implemention
     *
     * @returns ApplicationType
     */
    ApplicationType getType();

    FrameworkType getFrameworkType();

    BuildTool getBuildTool();

    /**
     * Returns build tools supported by a given application type
     *
     * @returns array of BuildToolType
    */
    BuildToolType[] getSupportedBuildTools();
}
